### ISSUE TITLE
Feature request: region as chromosome on its own.

### ISSUE THREAD

**Issue by zx8754** [zhanxw/seqminer#3]
It would be nice to be able to define a region as chromosome name on its own as below:

```R
tabix.read("GeneticMap1KG.txt.gz","chr1")
```
Currently it gives below message and reads in everything, not just `chr1`:
```R
This range does not conform 1:100-200 format -- skip chr1
```

**Comment by zhanxw** [comment]
Thanks. That's nice to have.

**Comment by zhanxw** [comment]
When "chr1" is specified as a range, R could read too many contents and could crash for running out of memory. 
I currently forbid specifying "chr1" as range, and only allow "chr:begin-end" format. Hope that works for now.

**Comment by zx8754** [comment]
The problem is we don't always know the start end for selected chr. Command line tabix accepts chr on its own.

**Comment by zhanxw** [comment]
How about seqminer automatically expand "chr1" to "chr1:1-N" (N is the biggest 32-bit integer)?
In that way, seqminer can provide equivalent results to tabix.

**Comment by zx8754** [comment]
OK, makes sense: chr1:1-2147483647

[What is the maximum value for a int32?](http://stackoverflow.com/questions/94591/what-is-the-maximum-value-for-a-int32)
