### ISSUE TITLE
Cannot install package “ERROR: no information for variable 'CXX11', 'CXX11STD' and 'CXX11FLAGS'”

### ISSUE THREAD

**Issue by isinaltinkaya** [zhanxw/seqminer#7]
[See issue on StackOverflow](https://stackoverflow.com/questions/57481285/how-to-fix-r-error-no-information-for-variable-cxx11-cxx11std-and-cxx11f?noredirect=1)

**Comment by zhanxw** [comment]
I don't know why... I expect that at least R can get CXX11 variable.

**Comment by zhanxw** [comment]
I have not heard updates on this, so I will close this issue for now.

**Comment by ahstram** [comment]
@isinaltinkaya, @zhanxw , please see the solution I posted in the identical issue https://github.com/zhanxw/seqminer/issues/11
