### ISSUE TITLE
Missing license version

### ISSUE THREAD

**Issue by jenzopr** [zhanxw/seqminer#9]
Dear maintainer,

We noticed that you list `GPL` as `License` in your `Description` file. Can you clarify the specific GPL version your package is licensed under (e.g. `GPL-2` or `GPL-3`)?

On behalf of bioconda and conda-forge teams,
Jens

#### Technical background
Your package is currently available on the [bioconda](https://bioconda.github.io/) conda channel. We'd like to migrated the package to [conda-forge](https://conda-forge.org/). conda-forge requires inclusion of the license text during packaging. The R distribution already contains some licenses, but `GPL` is not one of them (however, `GPL-2` and `GPL-3` are included). Let me know if you need further information.

**Comment by zhanxw** [comment]
We plan to use GPLv3. Thanks.

**Comment by jenzopr** [comment]
Great! Thanks a lot for the short notice 💯
